name: Awesome WomenTechmakers
title: WomenTechmakers Korea 2019
description: This is blog run by womentechmakers scholars 2019 Korea. (Jekflix is a template for Jekyll inspired by Netflix and made by Thiago Rossener.)
tags:
  - blog
  - womentecmakers
  - wtm
  - jekyll
  - netlify
email: youremail@xyz.com
disqus_username: disqus_username
show_hero: true
paginate: 9
