name: Women Techmakers Scholar Korea
title: Korea WTM Scholars Blog
description:
  - 우먼테크메이커스(Women Techmakers) 장학생들이 자율적으로 운영하는 블로그입니다.
tags:
  - blog
  - womentechmakers
  - 우먼 테크메이커스
  - 장학생
  - wtm
  - jekyll
email: youremail@xyz.com
disqus_username: disqus_username
show_hero: true
paginate: 12
